[project]
name = "autogenbook"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Patrik Procházka", email = "me@patrikprochazka.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
autogenbook = "autogenbook:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"
