import { screen, waitFor } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { describe, expect, it } from 'vitest';

import { renderRouterApp } from '@/test/router-test-utils';

// Kept as the only test in this file: mounting the `ManuscriptSheet` lazy chunk (CodeMirror +
// react-markdown/remark/rehype/KaTeX) a second time in the same file measurably hangs its
// second `outline.node` fetch under jsdom+MSW — a test-environment quirk, not a product bug (the
// underlying behavior is also covered by `manuscript-sheet-blocker.route.test.tsx`, split out for
// the same reason, and unit-tested directly in `use-debounced-mutation.test.ts`/`section-editor.test.tsx`).
const LONG = { timeout: 10000 };

describe('Studio editor pane (routed, MSW-backed) — read-only', () => {
  it('shows a read-only banner and disables the source editor while the node is drafting', async () => {
    renderRouterApp('/p/book-reinforcement-learning?node=rl-ch-2');

    expect(
      await screen.findByRole(
        'heading',
        { level: 1, name: /Multi-Agent Value Factorization & Game Theory/ },
        LONG,
      ),
    ).toBeInTheDocument();
    expect(await screen.findByText(/being generated by a run/i, {}, LONG)).toBeInTheDocument();

    await userEvent.setup().click(await screen.findByRole('tab', { name: 'Source' }, LONG));
    await waitFor(() => {
      expect(document.querySelector('.cm-content')).toHaveAttribute('aria-readonly', 'true');
    }, LONG);
  }, 15000);
});
