/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["system-health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["system-ready"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Files */
        get: operations["files-list_files"];
        put?: never;
        /** Upload File */
        post: operations["files-upload_file"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/files/{file_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get File */
        get: operations["files-get_file"];
        put?: never;
        post?: never;
        /** Delete File */
        delete: operations["files-delete_file"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/files/{file_id}/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get File Content */
        get: operations["files-get_file_content"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Projects */
        get: operations["projects-list_projects"];
        put?: never;
        /** Create Project */
        post: operations["projects-create_project"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Project */
        get: operations["projects-get_project"];
        put?: never;
        post?: never;
        /** Delete Project */
        delete: operations["projects-delete_project"];
        options?: never;
        head?: never;
        /** Update Project */
        patch: operations["projects-update_project"];
        trace?: never;
    };
    "/api/v1/projects/{project_id}/duplicate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Duplicate Project */
        post: operations["projects-duplicate_project"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/spec": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Project Spec */
        get: operations["projects-get_project_spec"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sources */
        get: operations["sources-list_sources"];
        put?: never;
        /** Add Source */
        post: operations["sources-add_source"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/sources/{source_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Source */
        get: operations["sources-get_source"];
        put?: never;
        post?: never;
        /** Remove Source */
        delete: operations["sources-remove_source"];
        options?: never;
        head?: never;
        /** Update Source */
        patch: operations["sources-update_source"];
        trace?: never;
    };
    "/api/v1/projects/{project_id}/outline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Outline Nodes */
        get: operations["outline-list_outline_nodes"];
        /** Replace Outline */
        put: operations["outline-replace_outline"];
        /** Create Outline Node */
        post: operations["outline-create_outline_node"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/outline/{node_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Outline Node */
        get: operations["outline-get_outline_node"];
        put?: never;
        post?: never;
        /** Delete Outline Node */
        delete: operations["outline-delete_outline_node"];
        options?: never;
        head?: never;
        /** Update Outline Node */
        patch: operations["outline-update_outline_node"];
        trace?: never;
    };
    "/api/v1/projects/{project_id}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs */
        get: operations["runs-list_runs"];
        put?: never;
        /** Create Run */
        post: operations["runs-create_run"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/outline/{node_id}/regenerate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Regenerate Node */
        post: operations["runs-regenerate_node"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["runs-get_run"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Run */
        post: operations["runs-cancel_run"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/exports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Export Run */
        post: operations["runs-export_run"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Run Events */
        get: operations["runs-list_run_events"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/artifacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Run Artifacts */
        get: operations["runs-list_run_artifacts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/events/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream Run Events */
        get: operations["runs-stream_run_events"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ArtifactKind
         * @enum {string}
         */
        ArtifactKind: "markdown" | "tex" | "pdf" | "structure_graph" | "book_structure" | "section" | "section_review" | "kb_sources" | "run_meta" | "llm_usage" | "audit_report" | "log" | "bib" | "other";
        /** Body_files-upload_file */
        "Body_files-upload_file": {
            /** File */
            file: string;
        };
        /** BookStructure */
        BookStructure: {
            /** Title */
            title: string;
            /** Summary */
            summary: string;
            /** N Pages */
            n_pages: number;
            /** Target Readers */
            target_readers: string;
            /** Equation Frequency Level */
            equation_frequency_level: number;
            /** Do Consider Outline */
            do_consider_outline: boolean;
            /** Do Consider Previous Sections */
            do_consider_previous_sections: boolean;
            /** Additional Requirements */
            additional_requirements: string;
            /** Max Depth */
            max_depth: number;
            /** Max Output Pages */
            max_output_pages: number;
            /** Childs */
            childs?: components["schemas"]["BookStructureNode"][];
        };
        /** BookStructureNode */
        BookStructureNode: {
            /** Title */
            title: string;
            /** Summary */
            summary: string;
            /** N Pages */
            n_pages: number;
            /** Needssubdivision */
            needsSubdivision: boolean;
            /** Childs */
            childs?: components["schemas"]["BookStructureNode"][];
            /** Structure Locked */
            structure_locked?: boolean | null;
        };
        /**
         * ExportRequestIn
         * @description Request body of `POST /runs/{id}/exports`.
         */
        ExportRequestIn: {
            /**
             * Format
             * @enum {string}
             */
            format: "latex" | "pdf";
        };
        /** File */
        File: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Filename */
            filename: string;
            /** Contenttype */
            contentType: string;
            /** Sizebytes */
            sizeBytes: number;
            /** Sha256 */
            sha256: string;
            kind: components["schemas"]["FileKind"];
            /** Kbeligible */
            kbEligible: boolean;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
        };
        /**
         * FileKind
         * @enum {string}
         */
        FileKind: "upload" | "artifact";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * MathLevel
         * @enum {string}
         */
        MathLevel: "introductory" | "rigorous" | "formal_proof" | "applied";
        /**
         * NodeStatus
         * @enum {string}
         */
        NodeStatus: "not_started" | "drafting" | "review_ready" | "compiled";
        /**
         * OutlineNode
         * @description Flat shape - one row, addressed by `parentId` + `orderIndex`.
         *
         *     `level`, `sectionNumber` and `cliKey` returned here are always the
         *     current tree shape's derived value (`api.domain.outline.
         *     assign_positions`), never a client-supplied one - a client can't set any
         *     of the three (`OutlineNodeCreate`/`OutlineNodeUpdate` don't accept them).
         *     The `cli_key` *column*, unlike `level`/`section_number`, is genuinely
         *     persisted for a node a run has imported/regenerated (`graph_import.py`'s
         *     `_new_node`) - `RunService.regenerate_node` reads that stored value back
         *     to detect outline drift since the node's base run. See `graph_import.
         *     py`'s module docstring for the full read/write story.
         */
        OutlineNode: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Parentid */
            parentId: string | null;
            /** Orderindex */
            orderIndex: number;
            /** Clikey */
            cliKey?: string | null;
            /** Title */
            title: string;
            /** Summary */
            summary: string;
            /** Level */
            level: number;
            /** Sectionnumber */
            sectionNumber: string;
            status: components["schemas"]["NodeStatus"];
            /** Targetpages */
            targetPages: number;
            /** Wordbudget */
            wordBudget: number;
            /** Actualwords */
            actualWords: number;
            /** Equationdensitylevel */
            equationDensityLevel: number;
            mathLevel: components["schemas"]["MathLevel"];
            /** Subprompt */
            subPrompt?: string | null;
            /** Contentmarkdown */
            contentMarkdown: string;
            /** Contentlatex */
            contentLatex: string;
            /** Ragcitations */
            ragCitations?: {
                [key: string]: unknown;
            }[];
            /** Reviewerscore */
            reviewerScore?: number | null;
            /** Reviewernotes */
            reviewerNotes?: string | null;
            /** Structurelocked */
            structureLocked: boolean;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /**
             * Updatedat
             * Format: date-time
             */
            updatedAt: string;
        };
        /** OutlineNodeCreate */
        OutlineNodeCreate: {
            /** Parentid */
            parentId?: string | null;
            /** Title */
            title: string;
            /** Orderindex */
            orderIndex?: number | null;
            /**
             * Summary
             * @default
             */
            summary?: string;
            /** Targetpages */
            targetPages?: number | null;
            /** Subprompt */
            subPrompt?: string | null;
            /** @default rigorous */
            mathLevel?: components["schemas"]["MathLevel"];
            /** Equationdensitylevel */
            equationDensityLevel?: number | null;
        };
        /**
         * OutlineNodeTree
         * @description `OutlineNode` with nested `children` instead of `parentId`/`orderIndex`.
         */
        OutlineNodeTree: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Parentid */
            parentId: string | null;
            /** Orderindex */
            orderIndex: number;
            /** Clikey */
            cliKey?: string | null;
            /** Title */
            title: string;
            /** Summary */
            summary: string;
            /** Level */
            level: number;
            /** Sectionnumber */
            sectionNumber: string;
            status: components["schemas"]["NodeStatus"];
            /** Targetpages */
            targetPages: number;
            /** Wordbudget */
            wordBudget: number;
            /** Actualwords */
            actualWords: number;
            /** Equationdensitylevel */
            equationDensityLevel: number;
            mathLevel: components["schemas"]["MathLevel"];
            /** Subprompt */
            subPrompt?: string | null;
            /** Contentmarkdown */
            contentMarkdown: string;
            /** Contentlatex */
            contentLatex: string;
            /** Ragcitations */
            ragCitations?: {
                [key: string]: unknown;
            }[];
            /** Reviewerscore */
            reviewerScore?: number | null;
            /** Reviewernotes */
            reviewerNotes?: string | null;
            /** Structurelocked */
            structureLocked: boolean;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /**
             * Updatedat
             * Format: date-time
             */
            updatedAt: string;
            /** Children */
            children?: components["schemas"]["OutlineNodeTree"][];
        };
        /**
         * OutlineNodeUpdate
         * @description Partial update of mutable fields. `level`, `sectionNumber`, `cliKey`
         *     and `actualWords` are server-derived - sending any of them (or any other
         *     unknown key) is rejected with 422.
         */
        OutlineNodeUpdate: {
            /** Parentid */
            parentId?: string | null;
            /** Orderindex */
            orderIndex?: number | null;
            /** Title */
            title?: string | null;
            /** Summary */
            summary?: string | null;
            status?: components["schemas"]["NodeStatus"] | null;
            /** Targetpages */
            targetPages?: number | null;
            /** Wordbudget */
            wordBudget?: number | null;
            /** Equationdensitylevel */
            equationDensityLevel?: number | null;
            mathLevel?: components["schemas"]["MathLevel"] | null;
            /** Subprompt */
            subPrompt?: string | null;
            /** Contentmarkdown */
            contentMarkdown?: string | null;
            /** Contentlatex */
            contentLatex?: string | null;
            /** Reviewerscore */
            reviewerScore?: number | null;
            /** Reviewernotes */
            reviewerNotes?: string | null;
            /** Structurelocked */
            structureLocked?: boolean | null;
        };
        /**
         * OutlineTreeReplaceNode
         * @description One node of a full outline replacement, nested, without ids (ids are
         *     assigned on write).
         */
        OutlineTreeReplaceNode: {
            /** Title */
            title: string;
            /**
             * Summary
             * @default
             */
            summary?: string;
            /** Targetpages */
            targetPages?: number | null;
            /** Subprompt */
            subPrompt?: string | null;
            /** @default rigorous */
            mathLevel?: components["schemas"]["MathLevel"];
            /** Equationdensitylevel */
            equationDensityLevel?: number | null;
            /** Children */
            children?: components["schemas"]["OutlineTreeReplaceNode"][];
        };
        /**
         * OutputFormat
         * @enum {string}
         */
        OutputFormat: "markdown" | "latex" | "pdf";
        /** Page[File] */
        Page_File_: {
            /** Items */
            items: components["schemas"]["File"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** Page[OutlineNodeTree] */
        Page_OutlineNodeTree_: {
            /** Items */
            items: components["schemas"]["OutlineNodeTree"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** Page[OutlineNode] */
        Page_OutlineNode_: {
            /** Items */
            items: components["schemas"]["OutlineNode"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** Page[ProjectSummary] */
        Page_ProjectSummary_: {
            /** Items */
            items: components["schemas"]["ProjectSummary"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** Page[RunArtifact] */
        Page_RunArtifact_: {
            /** Items */
            items: components["schemas"]["RunArtifact"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** Page[Run] */
        Page_Run_: {
            /** Items */
            items: components["schemas"]["Run"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** Page[Source] */
        Page_Source_: {
            /** Items */
            items: components["schemas"]["Source"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** Project */
        Project: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /** Subtitle */
            subtitle: string;
            /** Authors */
            authors: string[];
            /** Topic */
            topic: string;
            targetAudience: components["schemas"]["TargetAudience"];
            /** Totalpagesbudget */
            totalPagesBudget: number;
            /** Equationfrequencylevel */
            equationFrequencyLevel: number;
            /** Doconsideroutline */
            doConsiderOutline: boolean;
            /** Doconsiderprevioussections */
            doConsiderPreviousSections: boolean;
            outputFormat: components["schemas"]["OutputFormat"];
            /** Maxoutlinelevels */
            maxOutlineLevels: number;
            /** Additionalrequirements */
            additionalRequirements?: string | null;
            /** Sources */
            sources?: components["schemas"]["Source"][];
            /** Outline */
            outline?: components["schemas"]["OutlineNodeTree"][];
            /** Lastrunid */
            lastRunId?: string | null;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /**
             * Updatedat
             * Format: date-time
             */
            updatedAt: string;
        };
        /** ProjectCreate */
        ProjectCreate: {
            /** Title */
            title: string;
            /** Subtitle */
            subtitle: string;
            /** Authors */
            authors: string[];
            /** Topic */
            topic: string;
            /** @default graduate */
            targetAudience?: components["schemas"]["TargetAudience"];
            /**
             * Totalpagesbudget
             * @default 350
             */
            totalPagesBudget?: number;
            /**
             * Equationfrequencylevel
             * @default 4
             */
            equationFrequencyLevel?: number;
            /**
             * Doconsideroutline
             * @default true
             */
            doConsiderOutline?: boolean;
            /**
             * Doconsiderprevioussections
             * @default true
             */
            doConsiderPreviousSections?: boolean;
            /** @default markdown */
            outputFormat?: components["schemas"]["OutputFormat"];
            /**
             * Maxoutlinelevels
             * @default 3
             */
            maxOutlineLevels?: number;
            /** Additionalrequirements */
            additionalRequirements?: string | null;
            /** Sources */
            sources?: components["schemas"]["SourceCreate"][] | null;
            /** Outline */
            outline?: components["schemas"]["OutlineTreeReplaceNode"][] | null;
        };
        /** ProjectSummary */
        ProjectSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /** Subtitle */
            subtitle: string;
            /** Authors */
            authors: string[];
            /** Topic */
            topic: string;
            targetAudience: components["schemas"]["TargetAudience"];
            /** Totalpagesbudget */
            totalPagesBudget: number;
            /** Sourcescount */
            sourcesCount: number;
            /** Outlinenodecount */
            outlineNodeCount: number;
            /** Lastrunid */
            lastRunId?: string | null;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /**
             * Updatedat
             * Format: date-time
             */
            updatedAt: string;
        };
        /** ProjectUpdate */
        ProjectUpdate: {
            /** Title */
            title?: string | null;
            /** Subtitle */
            subtitle?: string | null;
            /** Authors */
            authors?: string[] | null;
            /** Topic */
            topic?: string | null;
            targetAudience?: components["schemas"]["TargetAudience"] | null;
            /** Totalpagesbudget */
            totalPagesBudget?: number | null;
            /** Equationfrequencylevel */
            equationFrequencyLevel?: number | null;
            /** Doconsideroutline */
            doConsiderOutline?: boolean | null;
            /** Doconsiderprevioussections */
            doConsiderPreviousSections?: boolean | null;
            outputFormat?: components["schemas"]["OutputFormat"] | null;
            /** Maxoutlinelevels */
            maxOutlineLevels?: number | null;
            /** Additionalrequirements */
            additionalRequirements?: string | null;
        };
        /**
         * RegenerateRequestIn
         * @description Request body of `POST /projects/{id}/outline/{nodeId}/regenerate`.
         */
        RegenerateRequestIn: {
            /** Promptmodifier */
            promptModifier?: string | null;
        };
        /** Run */
        Run: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Projectid
             * Format: uuid
             */
            projectId: string;
            kind: components["schemas"]["RunKind"];
            status: components["schemas"]["RunStatus"];
            options: components["schemas"]["RunOptionsOut"];
            /** Baserunid */
            baseRunId: string | null;
            /** Targetnodeid */
            targetNodeId: string | null;
            /** Exitcode */
            exitCode: number | null;
            /** Error */
            error: string | null;
            /** Totaltokens */
            totalTokens: number | null;
            /** Totalcostusd */
            totalCostUsd: number | null;
            /**
             * Queuedat
             * Format: date-time
             */
            queuedAt: string;
            /** Startedat */
            startedAt: string | null;
            /** Finishedat */
            finishedAt: string | null;
            /** Resumable */
            resumable: boolean;
        };
        /** RunArtifact */
        RunArtifact: {
            kind: components["schemas"]["ArtifactKind"];
            /** Relativepath */
            relativePath: string;
            /**
             * Fileid
             * Format: uuid
             */
            fileId: string;
            /** Filename */
            filename: string;
            /** Sizebytes */
            sizeBytes: number;
            /** Contenttype */
            contentType: string;
        };
        /** RunEvent */
        RunEvent: {
            /** Seq */
            seq: number;
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
            /** Level */
            level: string;
            /** Stage */
            stage: string;
            /** Message */
            message: string;
            /** Payload */
            payload?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * RunEventPage
         * @description `GET /runs/{id}/events`'s response envelope. Deliberately not `Page`:
         *     this endpoint pages by `seq` (a monotonically increasing cursor), not by
         *     row position, so `Page.offset` echoing `afterSeq` misrepresented a
         *     sequence cursor as a row offset (issue #61).
         */
        RunEventPage: {
            /** Items */
            items: components["schemas"]["RunEvent"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Afterseq */
            afterSeq: number;
        };
        /**
         * RunKind
         * @enum {string}
         */
        RunKind: "full" | "regenerate_section" | "export";
        /**
         * RunOptionsIn
         * @description Request body of `POST /projects/{id}/runs`. `output_format` defaults
         *     to the project's own `output_format` when omitted (resolved by
         *     `RunService.create`'s caller, not here).
         *
         *     `resume`, `exportTexOnly` and `rebuildKb` are deliberately not exposed
         *     here (issue #60): they only have meaningful semantics on a
         *     `regenerate_section`/`export` run resuming an existing work directory,
         *     which `RunService.regenerate_node`/`export` already set on the run's
         *     `RunOptions` themselves via `dataclasses.replace(base_run.options, ...)`.
         *     A fresh `full` run always starts a brand-new work directory, so
         *     `resume=True` would resume nothing, `exportTexOnly=True` has no base
         *     Markdown to skip regenerating, and `rebuildKb` has no pre-existing index
         *     to force a rebuild of.
         */
        RunOptionsIn: {
            /**
             * Outline
             * @default project
             * @enum {string}
             */
            outline?: "project" | "generate";
            /** Outputformat */
            outputFormat?: ("markdown" | "latex" | "pdf") | null;
            /**
             * Allowsubdivision
             * @default true
             */
            allowSubdivision?: boolean;
            /**
             * Enablewebrag
             * @default false
             */
            enableWebRag?: boolean;
            /**
             * Auditbook
             * @default false
             */
            auditBook?: boolean;
            /**
             * Auditbookmode
             * @default warn
             * @enum {string}
             */
            auditBookMode?: "off" | "warn" | "strict";
            /**
             * Legacytex
             * @default false
             */
            legacyTex?: boolean;
            /**
             * Failfastschema
             * @default false
             */
            failFastSchema?: boolean;
        };
        /** RunOptionsOut */
        RunOptionsOut: {
            /**
             * Outline
             * @enum {string}
             */
            outline: "project" | "generate";
            /**
             * Outputformat
             * @enum {string}
             */
            outputFormat: "markdown" | "latex" | "pdf";
            /** Allowsubdivision */
            allowSubdivision: boolean;
            /** Enablewebrag */
            enableWebRag: boolean;
            /** Auditbook */
            auditBook: boolean;
            /**
             * Auditbookmode
             * @enum {string}
             */
            auditBookMode: "off" | "warn" | "strict";
            /** Legacytex */
            legacyTex: boolean;
            /** Rebuildkb */
            rebuildKb: boolean;
            /** Failfastschema */
            failFastSchema: boolean;
            /** Resume */
            resume: boolean;
            /** Exporttexonly */
            exportTexOnly: boolean;
            /** Promptmodifier */
            promptModifier?: string | null;
        };
        /**
         * RunStatus
         * @enum {string}
         */
        RunStatus: "queued" | "running" | "succeeded" | "failed" | "cancelled";
        /** Source */
        Source: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Fileid
             * Format: uuid
             */
            fileId: string;
            /** Name */
            name: string;
            /** Sizebytes */
            sizeBytes: number;
            type: components["schemas"]["SourceType"];
            /** Chunkscount */
            chunksCount?: number | null;
            status: components["schemas"]["SourceStatus"];
            /**
             * Uploaddate
             * Format: date-time
             */
            uploadDate: string;
            /** Authors */
            authors?: string | null;
            /** Year */
            year?: string | null;
            /** Doi */
            doi?: string | null;
            /** Url */
            url?: string | null;
            /** Description */
            description?: string | null;
        };
        /** SourceCreate */
        SourceCreate: {
            /**
             * Fileid
             * Format: uuid
             */
            fileId: string;
            type?: components["schemas"]["SourceType"] | null;
            /** Authors */
            authors?: string | null;
            /** Year */
            year?: string | null;
            /** Doi */
            doi?: string | null;
            /** Url */
            url?: string | null;
            /** Description */
            description?: string | null;
        };
        /**
         * SourceStatus
         * @enum {string}
         */
        SourceStatus: "ready" | "indexed" | "error";
        /**
         * SourceType
         * @enum {string}
         */
        SourceType: "pdf" | "doc" | "ppt" | "md" | "txt" | "slides" | "arxiv" | "notes" | "bibtex" | "latex" | "url" | "book" | "dataset";
        /** SourceUpdate */
        SourceUpdate: {
            type?: components["schemas"]["SourceType"] | null;
            /** Authors */
            authors?: string | null;
            /** Year */
            year?: string | null;
            /** Doi */
            doi?: string | null;
            /** Url */
            url?: string | null;
            /** Description */
            description?: string | null;
        };
        /**
         * TargetAudience
         * @enum {string}
         */
        TargetAudience: "undergraduate" | "graduate" | "phd_researcher" | "industry_practitioner";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "system-health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    "system-ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    "files-list_files": {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                kind?: components["schemas"]["FileKind"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_File_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "files-upload_file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_files-upload_file"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["File"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "files-get_file": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                file_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["File"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "files-delete_file": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                file_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "files-get_file_content": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                file_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "projects-list_projects": {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_ProjectSummary_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "projects-create_project": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "projects-get_project": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "projects-delete_project": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "projects-update_project": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "projects-duplicate_project": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "projects-get_project_spec": {
        parameters: {
            query?: {
                format?: string;
                includeOutline?: boolean;
            };
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The project's spec, as plain text (`?format=txt`) or the CLI's `book_structure.json`-shaped JSON (`?format=json`). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookStructure"];
                    "text/plain": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "sources-list_sources": {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_Source_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "sources-add_source": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SourceCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Source"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "sources-get_source": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                source_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Source"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "sources-remove_source": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                source_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "sources-update_source": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                source_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SourceUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Source"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "outline-list_outline_nodes": {
        parameters: {
            query?: {
                format?: string;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_OutlineNode_"] | components["schemas"]["Page_OutlineNodeTree_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "outline-replace_outline": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OutlineTreeReplaceNode"][];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_OutlineNode_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "outline-create_outline_node": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OutlineNodeCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OutlineNode"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "outline-get_outline_node": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                node_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OutlineNode"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "outline-delete_outline_node": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                node_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "outline-update_outline_node": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                node_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OutlineNodeUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OutlineNode"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "runs-list_runs": {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_Run_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "runs-create_run": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunOptionsIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "runs-regenerate_node": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                node_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegenerateRequestIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "runs-get_run": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "runs-cancel_run": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "runs-export_run": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExportRequestIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "runs-list_run_events": {
        parameters: {
            query?: {
                afterSeq?: number;
                limit?: number;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunEventPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "runs-list_run_artifacts": {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_RunArtifact_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "runs-stream_run_events": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
