/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness check
         * @description **Implemented** (`api/presentation/routers/system.py:health`). Always returns `ok`; does not check dependencies.
         */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness check (verifies Postgres connectivity)
         * @description **Implemented** (`api/presentation/routers/system.py:ready`). Runs `SELECT 1` through the async session. `GET /api/v1/ready` also calls the object-storage adapter's `healthcheck()` once issue #3 lands.
         */
        get: operations["getReady"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List uploaded/artifact files */
        get: operations["listFiles"];
        put?: never;
        /** Upload a file */
        post: operations["uploadFile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/files/{fileId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                fileId: components["parameters"]["FileId"];
            };
            cookie?: never;
        };
        /** Get file metadata */
        get: operations["getFile"];
        put?: never;
        post?: never;
        /** Delete a file */
        delete: operations["deleteFile"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/files/{fileId}/content": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                fileId: components["parameters"]["FileId"];
            };
            cookie?: never;
        };
        /**
         * Download file bytes
         * @description Streamed response with `Content-Disposition: attachment`, `Content-Length` and `ETag: "<sha256>"`.
         */
        get: operations["getFileContent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List projects
         * @description Sorted by `updatedAt` descending.
         */
        get: operations["listProjects"];
        put?: never;
        /** Create a project */
        post: operations["createProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{projectId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        /** Get a project */
        get: operations["getProject"];
        put?: never;
        post?: never;
        /**
         * Delete a project
         * @description Cascades to sources, outline nodes and runs via foreign keys.
         */
        delete: operations["deleteProject"];
        options?: never;
        head?: never;
        /**
         * Update project metadata
         * @description Metadata fields only. `sources`/`outline` keys are rejected with 422 - they have their own endpoints (issues #5, #6).
         */
        patch: operations["updateProject"];
        trace?: never;
    };
    "/api/v1/projects/{projectId}/duplicate": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Duplicate a project
         * @description Title suffixed " (Copy)". Copies sources by reference (same `fileId`s) and deep-copies outline nodes with new ids.
         */
        post: operations["duplicateProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{projectId}/sources": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        /** List a project's attached sources */
        get: operations["listSources"];
        put?: never;
        /**
         * Attach an already-uploaded file to a project as a source
         * @description There is no indexing at upload time - the CLI builds its BM25 index per run (issue #9), so a new source starts `status: ready` with `chunksCount: null`, not the draft contract's `202 indexing`.
         */
        post: operations["addSource"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{projectId}/sources/{sourceId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
                sourceId: components["parameters"]["SourceId"];
            };
            cookie?: never;
        };
        /** Get a source */
        get: operations["getSource"];
        put?: never;
        post?: never;
        /**
         * Detach a source from the project
         * @description Removes the attachment; the underlying file is not deleted.
         */
        delete: operations["removeSource"];
        options?: never;
        head?: never;
        /** Update a source's bibliographic metadata */
        patch: operations["updateSource"];
        trace?: never;
    };
    "/api/v1/projects/{projectId}/outline": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        /** List outline nodes, flat or nested */
        get: operations["listOutlineNodes"];
        /**
         * Replace the whole outline tree
         * @description Deletes and recreates every node from a nested tree without ids (e.g. wizard step 2, or a client-side reorder). Returns the new flat list.
         */
        put: operations["replaceOutline"];
        /** Create one outline node */
        post: operations["createOutlineNode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{projectId}/outline/{nodeId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
                nodeId: components["parameters"]["NodeId"];
            };
            cookie?: never;
        };
        /**
         * Get an outline node
         * @description Includes full `contentMarkdown`/`contentLatex`/`ragCitations`.
         */
        get: operations["getOutlineNode"];
        put?: never;
        post?: never;
        /** Delete an outline node (cascades to descendants) */
        delete: operations["deleteOutlineNode"];
        options?: never;
        head?: never;
        /**
         * Update an outline node
         * @description Consolidates rename/content-edit/math-level/equation-density/budget/move into one generic PATCH, since they all mutate the same row. Editing `contentMarkdown` recomputes `actualWords` server-side.
         */
        patch: operations["updateOutlineNode"];
        trace?: never;
    };
    "/api/v1/projects/{projectId}/outline/{nodeId}/regenerate": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
                nodeId: components["parameters"]["NodeId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Regenerate one node's content, reusing the project's last run
         * @description Reuses `project.lastRunId`'s work directory and the CLI's `--resume` semantics; does not re-run structural planning. Sets the node `status` to `drafting` immediately.
         */
        post: operations["regenerateOutlineNode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{projectId}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        /** List a project's runs */
        get: operations["listRuns"];
        put?: never;
        /** Start a full generation run */
        post: operations["createRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{runId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        /** Get a run */
        get: operations["getRun"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{runId}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel a queued or running run
         * @description A queued run is cancelled immediately; a running one has `cancelRequested` set and its subprocess is terminated by the worker.
         */
        post: operations["cancelRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{runId}/events": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        /**
         * Poll accumulated run events
         * @description Polling fallback for clients that don't use the SSE stream.
         */
        get: operations["listRunEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{runId}/events/stream": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        /**
         * Server-Sent Events stream of run progress
         * @description SSE chosen over WebSocket because `app/nginx.conf`'s `location /api/` block has no `Upgrade`/`Connection: upgrade` headers, while SSE works over plain HTTP/1.1 unchanged. Event `id:` is the `RunEvent.seq`; the server honours a `Last-Event-ID` request header to resume a dropped connection. Event names: `log` (a `RunEvent` with `level`/`message`), `stage` (pipeline stage change), `section` (a leaf section finished), `done` (terminal, stream closes after). OpenAPI has no way to type per-event-name payloads; each event's `data:` is JSON shaped like `RunEvent` (see `RunEvent` below and `docs/WEB_API_REFERENCE.md` for the full per-event field list). The server polls `run_events` every second.
         */
        get: operations["streamRunEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{runId}/artifacts": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        /**
         * List files produced by a run
         * @description Download each artifact via `GET /api/v1/files/{fileId}/content`.
         */
        get: operations["listRunArtifacts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{runId}/exports": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Build a LaTeX/PDF export from a finished run, without regenerating content
         * @description Reuses the base run's work directory with `--resume --export-tex`; produces `tex`/`pdf` artifacts (issue #10) without touching any section content.
         */
        post: operations["exportRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description RFC 9457 problem details, `Content-Type: application/problem+json` (`api/core/errors.py`). */
        Problem: {
            /** @description Always `"about:blank"` today (no per-error-type documentation URIs yet). */
            type: string;
            title: string;
            status: number;
            detail?: string | null;
            /** @description The request path that produced the error. */
            instance: string;
        };
        /** @description Response of the implemented `GET /api/v1/health`. */
        HealthStatus: {
            /** @enum {string} */
            status: "ok";
        };
        /** @description Response of the implemented `GET /api/v1/ready` on success. */
        ReadyStatus: {
            /** @enum {string} */
            status: "ready";
        };
        PageOfFile: components["schemas"]["PageBase"] & {
            items: components["schemas"]["File"][];
        };
        PageOfProjectSummary: components["schemas"]["PageBase"] & {
            items: components["schemas"]["ProjectSummary"][];
        };
        PageOfSource: components["schemas"]["PageBase"] & {
            items: components["schemas"]["Source"][];
        };
        PageOfOutlineNode: components["schemas"]["PageBase"] & {
            items: components["schemas"]["OutlineNode"][];
        };
        PageOfOutlineNodeTree: components["schemas"]["PageBase"] & {
            items: components["schemas"]["OutlineNodeTree"][];
        };
        PageOfRun: components["schemas"]["PageBase"] & {
            items: components["schemas"]["Run"][];
        };
        PageOfRunEvent: components["schemas"]["PageBase"] & {
            items: components["schemas"]["RunEvent"][];
        };
        PageOfRunArtifact: components["schemas"]["PageBase"] & {
            items: components["schemas"]["RunArtifact"][];
        };
        /** @description Common envelope fields (`api/presentation/schemas/common.py:Page`); each `PageOf*` schema adds a typed `items`. */
        PageBase: {
            total: number;
            limit: number;
            offset: number;
        };
        /** @enum {string} */
        FileKind: "upload" | "artifact";
        File: {
            /** Format: uuid */
            id: string;
            filename: string;
            contentType: string;
            sizeBytes: number;
            sha256: string;
            kind: components["schemas"]["FileKind"];
            /** @description True when the extension is one the CLI's knowledge base indexes (`.pdf .docx .pptx .md .txt` - `rag_kb.py:SUPPORTED_EXTS`). */
            kbEligible: boolean;
            /** Format: date-time */
            createdAt: string;
        };
        /** @enum {string} */
        AudienceLevel: "undergraduate" | "graduate" | "phd_researcher" | "industry_practitioner";
        /** @enum {string} */
        OutputFormat: "markdown" | "latex" | "pdf";
        Project: {
            /** Format: uuid */
            id: string;
            title: string;
            subtitle: string;
            authors: string[];
            topic: string;
            targetAudience: components["schemas"]["AudienceLevel"];
            totalPagesBudget: number;
            equationFrequencyLevel: number;
            doConsiderOutline: boolean;
            doConsiderPreviousSections: boolean;
            outputFormat: components["schemas"]["OutputFormat"];
            maxOutlineLevels: number;
            /** @description CLI field with no frontend-mock equivalent (`additional_requirements`). */
            additionalRequirements?: string | null;
            sources: components["schemas"]["Source"][];
            /** @description Root-level outline nodes, nested. */
            outline: components["schemas"]["OutlineNodeTree"][];
            /** Format: uuid */
            lastRunId: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        /** @description Lighter shape for `GET /api/v1/projects` - not a subset type of `Project` in the frontend. */
        ProjectSummary: {
            /** Format: uuid */
            id: string;
            title: string;
            subtitle: string;
            authors: string[];
            topic: string;
            targetAudience: components["schemas"]["AudienceLevel"];
            totalPagesBudget: number;
            sourcesCount: number;
            outlineNodeCount: number;
            /** Format: uuid */
            lastRunId: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        /** @description `Project` fields minus server-assigned ones; optional `sources`/`outline` let the creation wizard attach files and author an outline atomically (issues #5, #6). */
        ProjectCreate: {
            title: string;
            subtitle: string;
            authors: string[];
            topic: string;
            /** @default graduate */
            targetAudience?: components["schemas"]["AudienceLevel"];
            /** @default 350 */
            totalPagesBudget?: number;
            /** @default 4 */
            equationFrequencyLevel?: number;
            /** @default true */
            doConsiderOutline?: boolean;
            /** @default true */
            doConsiderPreviousSections?: boolean;
            /** @default markdown */
            outputFormat?: components["schemas"]["OutputFormat"];
            /** @default 3 */
            maxOutlineLevels?: number;
            additionalRequirements?: string;
            sources?: components["schemas"]["SourceCreate"][];
            outline?: components["schemas"]["OutlineTreeReplace"];
        };
        /** @description Partial update of project metadata only. A `sources` or `outline` key in the body is rejected with 422 (they have their own endpoints). */
        ProjectUpdate: {
            title?: string;
            subtitle?: string;
            authors?: string[];
            topic?: string;
            targetAudience?: components["schemas"]["AudienceLevel"];
            totalPagesBudget?: number;
            equationFrequencyLevel?: number;
            doConsiderOutline?: boolean;
            doConsiderPreviousSections?: boolean;
            outputFormat?: components["schemas"]["OutputFormat"];
            maxOutlineLevels?: number;
            additionalRequirements?: string;
        };
        /** @enum {string} */
        SourceType: "pdf" | "doc" | "ppt" | "md" | "txt" | "slides" | "arxiv" | "notes" | "bibtex" | "latex" | "url" | "book" | "dataset";
        /**
         * @description `ready` until a run indexes it (`chunksCount` still `null`); `indexed`/ `error` are set from that run's `kb_sources.json` (issue #10).
         * @enum {string}
         */
        SourceStatus: "ready" | "indexed" | "error";
        RAGCitation: {
            id: string;
            sourceDoc: string;
            pageNumber?: number | null;
            sectionSnippet: string;
            relevanceScore: number;
            authorYear?: string | null;
        };
        /** @description A file attached to a project as a RAG source. */
        Source: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            fileId: string;
            /** @description The file's `filename`. */
            name: string;
            sizeBytes: number;
            type: components["schemas"]["SourceType"];
            chunksCount: number | null;
            status: components["schemas"]["SourceStatus"];
            /**
             * Format: date-time
             * @description The file's `createdAt`.
             */
            uploadDate: string;
            authors?: string | null;
            year?: string | null;
            doi?: string | null;
            url?: string | null;
            description?: string | null;
        };
        SourceCreate: {
            /** Format: uuid */
            fileId: string;
            type?: components["schemas"]["SourceType"];
            authors?: string;
            year?: string;
            doi?: string;
            url?: string;
            description?: string;
        };
        /** @description Bibliographic metadata only. */
        SourceUpdate: {
            authors?: string;
            year?: string;
            doi?: string;
            url?: string;
            description?: string;
        };
        /** @enum {string} */
        NodeStatus: "not_started" | "drafting" | "review_ready" | "compiled";
        /** @enum {string} */
        MathLevel: "introductory" | "rigorous" | "formal_proof" | "applied";
        /** @description Flat shape - one row, addressed by `parentId` + `orderIndex`. */
        OutlineNode: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            parentId: string | null;
            orderIndex: number;
            /** @description Positional key matching the CLI graph (`"1"`, `"1-2"`, `"1-2-3"` - `autogenbook/graph/doc_graph.py`), assigned once a run has processed this node. */
            readonly cliKey?: string | null;
            title: string;
            summary: string;
            /** @description 1 = Chapter, 2 = Section, 3 = Subsection - derived from the tree. */
            readonly level: number;
            /** @description e.g. "1.2.1" - derived from the tree. */
            readonly sectionNumber: string;
            status: components["schemas"]["NodeStatus"];
            targetPages: number;
            wordBudget: number;
            readonly actualWords: number;
            equationDensityLevel: number;
            mathLevel: components["schemas"]["MathLevel"];
            subPrompt?: string | null;
            contentMarkdown: string;
            contentLatex: string;
            ragCitations: components["schemas"]["RAGCitation"][];
            reviewerScore?: number | null;
            reviewerNotes?: string | null;
            /** @description False on nodes the CLI subdivided itself (`subdivide_graph`), which re-running a full generation may restructure further. */
            structureLocked: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        /** @description `OutlineNode` with nested `children` instead of `parentId`/`orderIndex`. */
        OutlineNodeTree: components["schemas"]["OutlineNode"] & {
            children: components["schemas"]["OutlineNodeTree"][];
        };
        OutlineNodeCreate: {
            /** Format: uuid */
            parentId: string | null;
            title: string;
            /** @description Defaults to append (last sibling). */
            orderIndex?: number;
            summary?: string;
            /** @description Default 1. */
            targetPages?: number;
            subPrompt?: string;
            /** @default rigorous */
            mathLevel?: components["schemas"]["MathLevel"];
            /** @description Defaults to the project's `equationFrequencyLevel`. */
            equationDensityLevel?: number;
        };
        /** @description Partial update of mutable fields. `level`, `sectionNumber`, `cliKey` and `actualWords` are server-derived - sending any of them is rejected with 422. */
        OutlineNodeUpdate: {
            /** Format: uuid */
            parentId?: string | null;
            orderIndex?: number;
            title?: string;
            summary?: string;
            status?: components["schemas"]["NodeStatus"];
            targetPages?: number;
            wordBudget?: number;
            equationDensityLevel?: number;
            mathLevel?: components["schemas"]["MathLevel"];
            subPrompt?: string;
            contentMarkdown?: string;
            contentLatex?: string;
            reviewerScore?: number;
            reviewerNotes?: string;
        };
        /** @description One node of a full outline replacement, nested, without ids (ids are assigned on write). Named separately from `OutlineTreeReplace` (rather than an inline array `items` schema) so `children` can `$ref` it recursively - a `$ref` into another schema's own `items` keyword isn't a resolvable named schema for codegen. */
        OutlineTreeReplaceNode: {
            title: string;
            summary?: string;
            targetPages?: number;
            subPrompt?: string;
            mathLevel?: components["schemas"]["MathLevel"];
            equationDensityLevel?: number;
            children?: components["schemas"]["OutlineTreeReplaceNode"][];
        };
        /** @description Root-level nodes of a full outline replacement, nested, without ids (ids are assigned on write). */
        OutlineTreeReplace: components["schemas"]["OutlineTreeReplaceNode"][];
        /** @enum {string} */
        RunKind: "full" | "regenerate_section" | "export";
        /** @enum {string} */
        RunStatus: "queued" | "running" | "succeeded" | "failed" | "cancelled";
        /**
         * @description Maps to the CLI's `--audit-mode` (`autogenbook/audit/latex_auditor.py`).
         * @enum {string}
         */
        AuditMode: "off" | "warn" | "strict";
        /** @description Body of `POST /api/v1/projects/{projectId}/runs`. */
        RunOptions: {
            /**
             * @description Only value today: build from the project's current outline rows. A literal spec input may be added later.
             * @default project
             * @enum {string}
             */
            outline?: "project";
            /** @description Defaults to the project's `outputFormat`. */
            outputFormat?: components["schemas"]["OutputFormat"];
            /**
             * @description Lets the CLI split oversized leaf sections further.
             * @default false
             */
            allowSubdivision?: boolean;
            /** @default warn */
            auditBookMode?: components["schemas"]["AuditMode"];
        };
        Run: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            projectId: string;
            kind: components["schemas"]["RunKind"];
            status: components["schemas"]["RunStatus"];
            /** @description The `RunOptions` this run was created with; for `regenerate_section` and `export` runs also carries internal fields (`resume`, `exportTexOnly`) set by the server, not by the client. */
            options: {
                [key: string]: unknown;
            };
            /**
             * Format: uuid
             * @description Set on `regenerate_section`/`export` runs - the run whose work dir is reused.
             */
            baseRunId: string | null;
            /**
             * Format: uuid
             * @description Set on `regenerate_section` runs.
             */
            targetNodeId: string | null;
            exitCode: number | null;
            error: string | null;
            totalTokens: number | null;
            totalCostUsd: number | null;
            /** @description False once this run's work directory has been reaped by retention cleanup. */
            resumable: boolean;
            /** Format: date-time */
            queuedAt: string;
            /** Format: date-time */
            startedAt: string | null;
            /** Format: date-time */
            finishedAt: string | null;
        };
        /** @description One row of `run_events`; also the JSON payload of the SSE `log` event. */
        RunEvent: {
            seq: number;
            /** Format: date-time */
            ts: string;
            /** @description e.g. `"info"`, `"warn"`, `"error"`. */
            level: string;
            /** @description Pipeline stage name, when applicable. */
            stage?: string | null;
            message: string;
            /** @description Event-specific extra data (e.g. `nodeId`/`cliKey` on a `section` event). */
            payload?: {
                [key: string]: unknown;
            } | null;
        };
        /** @enum {string} */
        ArtifactKind: "markdown" | "tex" | "pdf" | "structure_graph" | "book_structure" | "section" | "section_review" | "kb_sources" | "run_meta" | "llm_usage" | "audit_report" | "log" | "bib" | "other";
        RunArtifact: {
            kind: components["schemas"]["ArtifactKind"];
            /** @description Path within the run's work directory, e.g. `sections/1-2.md`. */
            relativePath: string;
            /** Format: uuid */
            fileId: string;
            filename: string;
            sizeBytes: number;
            contentType: string;
        };
        RegenerateRequest: {
            /** @description Appended to the node's `summary` in the reused `structure_graph.json` before the CLI resumes. */
            promptModifier?: string;
        };
        /** @enum {string} */
        ExportFormat: "latex" | "pdf";
        ExportRequest: {
            format: components["schemas"]["ExportFormat"];
        };
    };
    responses: never;
    parameters: {
        /** @description Page size, 1-200 (default 50). */
        Limit: number;
        Offset: number;
        ProjectId: string;
        FileId: string;
        SourceId: string;
        NodeId: string;
        RunId: string;
        OutlineFormat: "flat" | "tree";
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is up. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthStatus"];
                };
            };
        };
    };
    getReady: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Database (and, from issue */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyStatus"];
                };
            };
            /** @description A dependency (database today; object storage from issue #3) is unreachable. `api/core/errors.py:StorageError`. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    listFiles: {
        parameters: {
            query?: {
                /** @description Page size, 1-200 (default 50). */
                limit?: components["parameters"]["Limit"];
                offset?: components["parameters"]["Offset"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Page of files. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageOfFile"];
                };
            };
        };
    };
    uploadFile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description File stored (key `uploads/{fileId}/{filename}`), `kind=upload`. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["File"];
                };
            };
            /** @description Upload exceeds `MAX_UPLOAD_MB`. The partial object is deleted; no `File` row is created. */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    getFile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                fileId: components["parameters"]["FileId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description File metadata. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["File"];
                };
            };
            /** @description File not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    deleteFile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                fileId: components["parameters"]["FileId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description File deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description File not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description File is still referenced by a project source (issue #5) or a run artifact (issue #10). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    getFileContent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                fileId: components["parameters"]["FileId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description File bytes. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
            /** @description File not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    listProjects: {
        parameters: {
            query?: {
                /** @description Page size, 1-200 (default 50). */
                limit?: components["parameters"]["Limit"];
                offset?: components["parameters"]["Offset"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Page of project summaries. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageOfProjectSummary"];
                };
            };
        };
    };
    createProject: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreate"];
            };
        };
        responses: {
            /** @description Project created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            /** @description Validation failed (e.g. `totalPagesBudget` outside 5-2000, `maxOutlineLevels`/`equationFrequencyLevel` outside 1-5). */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    getProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Full project, including embedded `sources` and `outline` (tree). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            /** @description Project not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    deleteProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Project deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Project not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    updateProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectUpdate"];
            };
        };
        responses: {
            /** @description Updated project. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            /** @description Project not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Validation failed, or `sources`/`outline` present in the body. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    duplicateProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description New, duplicated project. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            /** @description Source project not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    listSources: {
        parameters: {
            query?: {
                /** @description Page size, 1-200 (default 50). */
                limit?: components["parameters"]["Limit"];
                offset?: components["parameters"]["Offset"];
            };
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Page of sources. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageOfSource"];
                };
            };
            /** @description Project not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    addSource: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SourceCreate"];
            };
        };
        responses: {
            /** @description Source attached. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Source"];
                };
            };
            /** @description Project or file not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description This file is already attached to the project. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description File is not KB-eligible (`kbEligible: false` - extension outside `.pdf .docx .pptx .md .txt`). */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    getSource: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
                sourceId: components["parameters"]["SourceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Source, including `chunksCount`/`status` once indexed by a run. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Source"];
                };
            };
            /** @description Project or source not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    removeSource: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
                sourceId: components["parameters"]["SourceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Source detached. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Project or source not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    updateSource: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
                sourceId: components["parameters"]["SourceId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SourceUpdate"];
            };
        };
        responses: {
            /** @description Updated source. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Source"];
                };
            };
            /** @description Project or source not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    listOutlineNodes: {
        parameters: {
            query?: {
                format?: components["parameters"]["OutlineFormat"];
                /** @description Page size, 1-200 (default 50). */
                limit?: components["parameters"]["Limit"];
                offset?: components["parameters"]["Offset"];
            };
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description `items` is the flat node list (default `format=flat`) or the root-level nested nodes (`format=tree`, each with `children`); `total` is always the flat node count. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageOfOutlineNode"] | components["schemas"]["PageOfOutlineNodeTree"];
                };
            };
            /** @description Project not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    replaceOutline: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OutlineTreeReplace"];
            };
        };
        responses: {
            /** @description New outline, flat. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageOfOutlineNode"];
                };
            };
            /** @description Project not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description A node's depth exceeds `project.maxOutlineLevels`. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    createOutlineNode: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OutlineNodeCreate"];
            };
        };
        responses: {
            /** @description New outline node. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OutlineNode"];
                };
            };
            /** @description Project (or parent node) not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Depth would exceed `project.maxOutlineLevels`. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    getOutlineNode: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
                nodeId: components["parameters"]["NodeId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Outline node. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OutlineNode"];
                };
            };
            /** @description Project or node not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    deleteOutlineNode: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
                nodeId: components["parameters"]["NodeId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Node and its subtree deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Project or node not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    updateOutlineNode: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
                nodeId: components["parameters"]["NodeId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OutlineNodeUpdate"];
            };
        };
        responses: {
            /** @description Updated outline node. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OutlineNode"];
                };
            };
            /** @description Project or node not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description A server-derived field (`level`, `sectionNumber`, `cliKey`, `actualWords`) was present in the body, or the requested `parentId` move would exceed `project.maxOutlineLevels`. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    regenerateOutlineNode: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
                nodeId: components["parameters"]["NodeId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegenerateRequest"];
            };
        };
        responses: {
            /** @description Regeneration run queued, kind `regenerate_section`. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            /** @description Project or node not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description No successful prior run to resume from, its work directory is gone, or the project already has an active run. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    listRuns: {
        parameters: {
            query?: {
                /** @description Page size, 1-200 (default 50). */
                limit?: components["parameters"]["Limit"];
                offset?: components["parameters"]["Offset"];
            };
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Page of runs. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageOfRun"];
                };
            };
            /** @description Project not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    createRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["RunOptions"];
            };
        };
        responses: {
            /** @description Run queued, kind `full`. Picked up by a worker within one poll interval. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            /** @description Project not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description The project already has a queued or running run. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    getRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Run, including `resumable` (false once its work dir has been reaped). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            /** @description Run not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    cancelRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cancellation accepted. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            /** @description Run not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Run is already in a terminal state (`succeeded`/`failed`/`cancelled`). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    listRunEvents: {
        parameters: {
            query?: {
                /** @description Only return events with `seq` greater than this value. */
                afterSeq?: number;
                /** @description Page size, 1-200 (default 50). */
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path: {
                runId: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Page of run events, ordered by `seq` ascending. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageOfRunEvent"];
                };
            };
            /** @description Run not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    streamRunEvents: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Event stream, open until the run reaches a terminal state. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            /** @description Run not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    listRunArtifacts: {
        parameters: {
            query?: {
                /** @description Page size, 1-200 (default 50). */
                limit?: components["parameters"]["Limit"];
                offset?: components["parameters"]["Offset"];
            };
            header?: never;
            path: {
                runId: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Page of run artifacts. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageOfRunArtifact"];
                };
            };
            /** @description Run not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    exportRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExportRequest"];
            };
        };
        responses: {
            /** @description Export run queued, kind `export`. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            /** @description Run not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Base run is not `succeeded`, its work dir is gone, or the project has an active run. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
}
