from __future__ import annotations

import uuid
from collections.abc import AsyncIterator, Sequence
from typing import BinaryIO, Protocol

from datetime import datetime

from api.domain.models import File, OutlineNode, Project, Run, RunArtifact, RunEvent, Source


class ProjectRepository(Protocol):
    async def get(self, project_id: uuid.UUID) -> Project | None: ...

    async def list(self, limit: int, offset: int) -> tuple[list[Project], int]: ...

    async def add(self, project: Project) -> Project: ...

    async def update(self, project: Project) -> Project: ...

    async def delete(self, project_id: uuid.UUID) -> None: ...

    async def sources_count(self, project_id: uuid.UUID) -> int: ...

    async def outline_node_count(self, project_id: uuid.UUID) -> int: ...


class FileStorage(Protocol):
    async def put(
        self,
        key: str,
        stream: BinaryIO,
        content_type: str,
        size_hint: int | None = None,
    ) -> None: ...

    async def open(self, key: str) -> AsyncIterator[bytes]: ...

    async def delete(self, key: str) -> None: ...

    async def exists(self, key: str) -> bool: ...

    async def healthcheck(self) -> None: ...


class FileRepository(Protocol):
    async def add(self, file: File) -> None: ...

    async def get(self, file_id: uuid.UUID) -> File | None: ...

    async def list(self, limit: int, offset: int) -> tuple[Sequence[File], int]: ...

    async def delete(self, file: File) -> None: ...

    async def is_referenced(self, file_id: uuid.UUID) -> bool: ...


class SourceRepository(Protocol):
    async def add(self, source: Source) -> Source: ...

    async def get(self, project_id: uuid.UUID, source_id: uuid.UUID) -> Source | None: ...

    async def get_by_project_and_file(
        self, project_id: uuid.UUID, file_id: uuid.UUID
    ) -> Source | None: ...

    async def list(
        self, project_id: uuid.UUID, limit: int, offset: int
    ) -> tuple[list[Source], int]: ...

    async def list_all(self, project_id: uuid.UUID) -> list[Source]: ...

    async def update(self, source: Source) -> Source: ...
    # No hard `delete`: `DELETE /projects/{id}/sources/{sourceId}` is a soft
    # delete (`deleted_at` set via `update`), so a removed row stays around
    # for audit purposes and to keep the file's `is_referenced` check honest
    # about what's still attached. Project deletion still hard-deletes every
    # row (soft-deleted or not) via the ORM cascade on `ProjectRecord`.


class OutlineRepository(Protocol):
    async def list(self, project_id: uuid.UUID) -> list[OutlineNode]: ...

    async def get(self, node_id: uuid.UUID) -> OutlineNode | None: ...

    async def add(self, node: OutlineNode) -> OutlineNode: ...

    async def update(self, node: OutlineNode) -> OutlineNode: ...

    async def delete_subtree(self, project_id: uuid.UUID, root_id: uuid.UUID) -> None: ...

    async def replace_all(
        self, project_id: uuid.UUID, nodes: Sequence[OutlineNode]
    ) -> list[OutlineNode]: ...

    async def reorder(
        self,
        project_id: uuid.UUID,
        parent_id: uuid.UUID | None,
        ordered_ids: Sequence[uuid.UUID],
    ) -> None: ...

    async def count(self, project_id: uuid.UUID) -> int: ...


class RunRepository(Protocol):
    async def get(self, run_id: uuid.UUID) -> Run | None: ...

    async def get_active_for_project(self, project_id: uuid.UUID) -> Run | None: ...

    async def list(
        self, project_id: uuid.UUID, limit: int, offset: int
    ) -> tuple[list[Run], int]: ...

    async def add(self, run: Run) -> Run: ...

    async def update(self, run: Run) -> Run: ...

    async def list_stale_work_dirs(self, cutoff: datetime) -> list[str]: ...

    async def rollback(self) -> None: ...


class RunEventRepository(Protocol):
    async def append_batch(self, run_id: uuid.UUID, events: Sequence[RunEvent]) -> None: ...

    async def list(
        self, run_id: uuid.UUID, after_seq: int, limit: int
    ) -> tuple[list[RunEvent], int]: ...

    async def list_after(
        self, run_id: uuid.UUID, after_seq: int, limit: int
    ) -> list[RunEvent]: ...

    async def max_seq(self, run_id: uuid.UUID) -> int: ...


class RunArtifactRepository(Protocol):
    async def add(self, artifact: RunArtifact) -> RunArtifact: ...

    async def list(
        self, run_id: uuid.UUID, limit: int, offset: int
    ) -> tuple[list[RunArtifact], int]: ...

    async def delete_by_run(self, run_id: uuid.UUID) -> None: ...


class RunQueue(Protocol):
    async def claim(self, worker_id: str) -> Run | None: ...

    async def heartbeat(self, run_id: uuid.UUID) -> None: ...

    async def release(self, run_id: uuid.UUID) -> None: ...

    async def requeue_stale(self, older_than_s: float) -> int: ...
