from __future__ import annotations

import uuid
from collections.abc import AsyncIterator, Sequence
from typing import BinaryIO, Protocol

from api.domain.models import File, Project


class ProjectRepository(Protocol):
    async def get(self, project_id: uuid.UUID) -> Project | None: ...

    async def list(self, limit: int, offset: int) -> tuple[list[Project], int]: ...

    async def add(self, project: Project) -> Project: ...

    async def update(self, project: Project) -> Project: ...

    async def delete(self, project_id: uuid.UUID) -> None: ...

    async def sources_count(self, project_id: uuid.UUID) -> int: ...

    async def outline_node_count(self, project_id: uuid.UUID) -> int: ...


class FileStorage(Protocol):
    async def put(
        self,
        key: str,
        stream: BinaryIO,
        content_type: str,
        size_hint: int | None = None,
    ) -> None: ...

    async def open(self, key: str) -> AsyncIterator[bytes]: ...

    async def delete(self, key: str) -> None: ...

    async def exists(self, key: str) -> bool: ...

    async def healthcheck(self) -> None: ...


class FileRepository(Protocol):
    async def add(self, file: File) -> None: ...

    async def get(self, file_id: uuid.UUID) -> File | None: ...

    async def list(self, limit: int, offset: int) -> tuple[Sequence[File], int]: ...

    async def delete(self, file: File) -> None: ...

    async def is_referenced(self, file_id: uuid.UUID) -> bool: ...
